VALID_TITLES = ['Expense', 'Income']

VALID_CATEGORIES = [
    'Ăn uống',
    'Hoá đơn & Tiện ích',
    'Hoá đơn điện thoại',
    'Hoá đơn nước',
    'Hoá đơn điện',
    'Hoá đơn gas',
    'Hoá đơn TV',
    'Hoá đơn internet',
    'Thuê nhà',
    'Hoá đơn tiện ích khác',
    'Di chuyển',
    'Bảo dưỡng xe',
    'Mua sắm',
    'Đồ dùng cá nhân',
    'Đồ gia dụng',
    'Làm đẹp',
    'Gia đình',
    'Sửa & trang trí nhà',
    'Dịch vụ gia đình',
    'Vật nuôi',
    'Sức khỏe',
    'Khám sức khoẻ',
    'Thể dục thể thao',
    'Giáo dục',
    'Giải trí',
    'Dịch vụ trực tuyến',
    'Vui - chơi',
    'Quà tặng & Quyên góp',
    'Bảo hiểm',
    'Đầu tư',
    'Các chi phí khác',
    'Tiền chuyển đi',
    'Trả lãi',
    'Tiết kiệm',
    'Hẹn hò',
    'Công tác phí',
    'Du lịch',
    'DL Di chuyển',
    'DL Ăn uống',
    'DL Lưu trú',
    'DL Mua sắm',
    'DL Vui chơi',
    'Tiêu tết',
    'Tết ăn uống',
    'Mừng tuổi',
    'Tết vui chơi',
    'Tết mua sắm',
]

CATEGORY_KEYWORDS = [
    (['highland', 'starbucks', 'cafe', 'cà phê', 'caphe', 'cơm', 'pho', 'phở', 'bún', 'bun ', 'ăn ', 'an uong', 'trà sữa', 'tra sua', 'coffee', 'ăn uống'], 'Ăn uống'),
    (['grab', 'be xe', 'xăng', 'xang', 'petrol', 'taxi', 'bus', 'xe ôm', 'di chuyển', 'goto', 'xanh sm'], 'Di chuyển'),
    (['shopee', 'lazada', 'tiki', 'mua sắm', 'uniqlo', 'mall'], 'Mua sắm'),
    (['điện lực', 'evn', 'tiền điện', 'hoa don dien'], 'Hoá đơn điện'),
    (['nước', 'sawaco', 'tiền nước'], 'Hoá đơn nước'),
    (['internet', 'fpt', 'viettel', 'vnpt'], 'Hoá đơn internet'),
    (['netflix', 'spotify', 'youtube', 'icloud', 'openai', 'cursor'], 'Dịch vụ trực tuyến'),
    (['gym', 'yoga', 'bơi', 'pickleball'], 'Thể dục thể thao'),
    (['grabfood', 'shopeefood', 'baemin'], 'Ăn uống'),
    (['khách sạn', 'hotel', 'airbnb'], 'DL Lưu trú'),
    (['vé máy bay', 'vietnam airlines', 'vietjet', 'bamboo'], 'DL Di chuyển'),
]
